---
- hosts: pcnodo1
  become: true
  user: ansible
  gather_facts: no
  tasks:
  - name: Gather facts
    setup:
    
  - name: Display gathered facts
    debug:
      var: ansible_facts

  - name: Generate detailed inventory
    copy:
      content: |
        {
          "all": {
            "hosts": {
              "{{ ansible_hostname }}": {
                "ansible_host": "{{ ansible_host }}",
                "ansible_connection": "{{ ansible_connection }}",
                "ansible_user": "{{ ansible_user }}",
                "ansible_python_interpreter": "{{ ansible_python_interpreter }}",
                "ansible_distribution": "{{ ansible_distribution }}",
                "ansible_distribution_version": "{{ ansible_distribution_version }}",
                "ansible_architecture": "{{ ansible_architecture }}",
                "ansible_os_family": "{{ ansible_os_family }}",
                "ansible_kernel": "{{ ansible_kernel }}",
                "ansible_selinux": "{{ ansible_selinux }}",
                "ansible_virtualization_type": "{{ ansible_virtualization_type | default('') }}",
                "ansible_virtualization_role": "{{ ansible_virtualization_role | default('') }}",
                "ansible_virtualization": "{{ ansible_virtualization | default('') }}"
              }
            }
          }
        }
      dest: /home/ansible/detailed_inventory.json